title: "Feature Request: "
labels: [ "feature request", ]
body:
  - type: markdown
    attributes:
      value: |
        <!--- Logo and Header -->
        <div align="center">  
        <picture>
          <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/Lennolium/swiftGuard/main/img/banner/banner_dark.png" 
        width="500vw">
          <source media="(prefers-color-scheme: light)" 
        srcset="https://raw.githubusercontent.com/Lennolium/swiftGuard/main/img/banner/banner_light.png" 
        width="500vw">
          <img alt="swiftGuard banner" src="https://raw.githubusercontent.com/Lennolium/swiftGuard/main/img/banner/banner_light.png" 
        width="500vw">
        </picture>
        </div>
        
        <h2 align="center">Feature Request Submit Form</h2>
        <div align="center">
          Provide the following information properly, which will help me to address and incorporate your idea into the project. 
          If you need further help with this form, please do not hesitate and contact me via <a href="mailto:swiftguard@lennolium.dev">email</a>.
          Also make sure to check the the discussion forum for similar feature requests before submitting this form to avoid duplicates.
          For <b>issues regarding the package</b>, please open a new issue in the <a href="https://github.com/Lennolium/swiftGuard/issues/new/choose">Issues tab</a>. 
          <br>
          For all ideas, feature requests and  future plans, please use this form.
          <br>
          <br>
        
          <a href="https://github.com/Lennolium/swiftGuard/discussions" > 
            <img src="https://img.shields.io/github/discussions/Lennolium/swiftGuard?style=flat-square&color=deepskyblue" alt="discussions" >
          </a>
        
        </div>
        <br>
        <br>


  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What do you want to improve or add?
      options:
        - Application
        - Features/Functionality
        - Documentation
        - Code Quality
        - Future Plans
        - Development/Contributing
        - Other
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br>

  - type: textarea
    id: idea
    attributes:
      label: Idea
      description: Here you specify your idea or feature request and provide detailed information. You can also attach screenshots and files here.
      placeholder: I have an idea ...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br>

  - type: textarea
    id: other-info
    attributes:
      label: Further Information
      description: Feel free to add any further information maybe needed here.
      render: shell

  - type: markdown
    attributes:
      value: |
        <br>

  - type: checkboxes
    id: terms
    attributes:
      label: Agreements
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Lennolium/swiftGuard/blob/master/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
        - label: I confirm that I have searched the discussion tab for similar questions and this is not a duplicate.
          required: true
