name: "\U0001F41B Report an Issue"
description: "For general issues and bugs regarding the application."
title: "Issue: "
labels: [ "bug", ]
assignees:
  - Lennolium
body:
  - type: markdown
    attributes:
      value: |
        <!--- Logo and Header -->
         <div align="center">  
         <picture>
           <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/Lennolium/swiftGuard/main/img/banner/banner_dark.png" 
         width="500vw">
           <source media="(prefers-color-scheme: light)" 
         srcset="https://raw.githubusercontent.com/Lennolium/swiftGuard/main/img/banner/banner_light.png" 
         width="500vw">
           <img alt="swiftGuard banner" src="https://raw.githubusercontent.com/Lennolium/swiftGuard/main/img/banner/banner_light.png" 
         width="500vw">
         </picture>
         </div>
        
         <h2 align="center">General Issue Submit Form</h2>
         <div align="center">
           Provide the following information properly, which will help me to resolve your issue quickly.
           If you need further help with this form, please do not hesitate and contact me via <a href="mailto:swiftGuard@lennolium.dev">email</a>.
           Also make sure to check the issues tab for similar issues before submitting this form to avoid duplicates. 
           For reporting all <b>general questions and ideas</b>, please open a discussion in the <a href="https://github.com/Lennolium/swiftGuard/discussions/new/choose">Discussion tab</a>.
           <br>
           <br>
        
           <a href="https://github.com/Lennolium/swiftGuard/issues" > 
             <img src="https://img.shields.io/github/issues-raw/Lennolium/swiftGuard?style=flat-square&label=Open%20Issues&color=deepskyblue" alt="open issues" >
           </a>
        
           <a href="https://github.com/Lennolium/swiftGuard/issues?q=is%3Aissue+is%3Aclosed" > 
             <img src="https://img.shields.io/github/issues-closed-raw/Lennolium/swiftGuard?style=flat-square&label=Closed%20Issues&color=aliceblue" alt="closed issues" >
           </a>  
        
         </div>
         <br>
         <br>

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: "What kind of issue are you reporting?"
      multiple: false
      options:
        - Application Crash
        - Bug
        - UI/UX Glitch
        - Connection Error
        - Installation Issues
        - Bad Performance
        - Compatibility Issues
        - Documentation unclear/wrong
        - Other
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br>

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Also tell us briefly about the issue and provide all necessary information. You can also attach screenshots and files here."
      placeholder: I'm facing an issue with ...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br>

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: "Which operating system are you using? Please specify the distro if you are using Linux."
      multiple: false
      options:
        - macOS
        - Linux
        - Windows
        - Other
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br>

  - type: input
    id: os-version
    attributes:
      label: Operating System Version
      description: "Which version of the OS are you using? (e.g. macOS 12.0.1 / Monterey, Windows 11, Ubuntu 21.10, ...)"
      placeholder: Version number or name

  - type: markdown
    attributes:
      value: |
        <br>

  - type: dropdown
    id: os-arch
    attributes:
      label: Operating System Architecture
      description: "Which architecture is your OS running on? (For macOS, open `Terminal` and type `uname -m`.)"
      multiple: false
      options:
        - arm64
        - x86_64
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br>

  - type: dropdown
    id: install
    attributes:
      label: Installation Method
      description: "How did you install the application?"
      multiple: false
      options:
        - Release (GitHub)
        - From Source (GitHub)
        - Other (please specify)
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br>

  - type: input
    id: app-version
    attributes:
      label: Application Version
      description: "What version of the application are you running? Click the `Question Mark` icon or check logs at `~/Library/Logs/dev.lennolium.swiftguard/swiftguard.log`."
      placeholder: Latest, 0.1.0, 0.0.1, Legacy, ...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br>

  - type: textarea
    id: other-info
    attributes:
      label: Further Information
      description: "Please paste the last 50 lines of your log file `~/Library/Logs/dev.lennolium.swiftguard/swiftguard.log` here."
      render: shell

  - type: markdown
    attributes:
      value: |
        <br>

  - type: checkboxes
    id: terms
    attributes:
      label: Agreements
      description: "By submitting this issue, you acknowledge that you have read, understood, and agreed to the following terms:"
      options:
        - label: I have read and agree to follow this project's [Code of Conduct](https://github.com/Lennolium/swiftGuard/blob/master/.github/CODE_OF_CONDUCT.md).
          required: true
        - label: I confirm that I have searched the [Issue Tracker](https://github.com/Lennolium/swiftGuard/blob/master/.github/CODE_OF_CONDUCT.md) for similar issues and this is __not__ a duplicate.
          required: true
        - label: I am not reporting a personal or third party security vulnerability. If you are, read the [Security Policy](https://github.com/Lennolium/swiftGuard/blob/main/.github/SECURITY.md).
          required: true
        - label: _(Optional)_ I want to appear in the commit description as a contributor to the bug fix.
          required: false
